version: "3.7"

services:
  cakes_frontend_prod:
    container_name: cakes_frontend_prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"

  strapi_prod:
    container_name: strapi_prod
    image: strapi/strapi
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    volumes:
      - ./app:/srv/app
    depends_on:
      - mongo
    command: "strapi start"

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data/db:/app/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    ports:
      - "27017:27017"
